### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by adfsklodsfhnuisgyb** [ShaneBeee/Sk-Perm#1]
Hi.
* When i testing the addon, i created a new group. That gived me syntaxes errors *(i don't record, because server is now offline)*. When i tried to give a permission to me, i don't gived the permission. Don't gived any console error, but don't gived me the permission.

* When i gived the permission, i tried a command with the same permission, and said i don't have permission. When i looped my permissions, i can't find the permission.

*-* Sorry for bad english, i'm brazilian.

**Comment by ShaneBeee** [comment]
Im going to need some more info here.
For example:
Spigot Version
Skript Version
Sk-Perm Version

Are you running vault?
Which permission plugin are you using?

> * When i testing the addon, i created a new group. That gived me syntaxes errors _(i don't record, because server is now offline)_. 

Im going to need to see the errors. Without seeing your code and/or errors, there's really not much I can do to help.

**Comment by adfsklodsfhnuisgyb** [comment]
Spigot version: 1.8.8
Skript version 2.2dev37
Sk-Perm version: Latest
Vault: running
Permission plugin: I don't use

**Comment by ShaneBeee** [comment]
> Permission plugin: I don't use

Well that is why. This add-on will only work if Vault and a permission plugin is present.

**Comment by adfsklodsfhnuisgyb** [comment]
Which permission plugin do you recommend?

**Comment by ShaneBeee** [comment]
The basic Vault hooks will work with any permission plugin (that hooks into Vault)
This plugin also has extra syntaxes for a few specific ones:
- PermissionsEX
- LuckPerms
- UltraPermissions

I would recommend either PermissionsEX (PEX) or LuckPerms

**Comment by AdxmGG** [comment]
Is group manager supported too?

**Comment by adfsklodsfhnuisgyb** [comment]
thank you ^^

**Comment by adfsklodsfhnuisgyb** [comment]
> Is group manager supported too?

i guess so

**Comment by adfsklodsfhnuisgyb** [comment]
https://www.spigotmc.org/resources/ultra-permissions.42678/
This is the specificied "Ultra Permissions", right?

> The basic Vault hooks will work with any permission plugin.
> This plugin also has extra syntaxes for a few specific ones:
> 
> * PermissionsEX
> * LuckPerms
> * UltraPermissions
> 
> I would recommend either PermissionsEX (PEX) or LuckPerms

**Comment by ShaneBeee** [comment]
> Is group manager supported too?

For the basic Vault syntaxes yes, as this addon will support any permission plugin that hooks into vault.
But there are only limited syntaxes for the vault ones.

The other 3 I listed have more syntaxes

**Comment by ShaneBeee** [comment]
> https://www.spigotmc.org/resources/ultra-permissions.42678/
> This is the specificied "Ultra Permissions", right?
> 
> > The basic Vault hooks will work with any permission plugin.
> > This plugin also has extra syntaxes for a few specific ones:
> > 
> > * PermissionsEX
> > * LuckPerms
> > * UltraPermissions
> > 
> > I would recommend either PermissionsEX (PEX) or LuckPerms

yes

**Comment by adfsklodsfhnuisgyb** [comment]
thx

**Comment by ShaneBeee** [comment]
You're very welcome :)
