### ISSUE TITLE
Timed permissions and group

### ISSUE THREAD

**Issue by adfsklodsfhnuisgyb** [ShaneBeee/Sk-Perm#2]
It's possible to give a timed group or permission to player with Sk-Perm?

**Comment by ShaneBeee** [comment]
Yes, but it depends on which permission plugin you use. 
If you use PEX, it doesn't seem to work (this is an issue with PEX)
With LuckPerms and I believe UltraPermissions it works just fine

https://skripthub.net/docs/?id=3520
https://skripthub.net/docs/?id=3525

**Comment by adfsklodsfhnuisgyb** [comment]
thx

**Comment by adfsklodsfhnuisgyb** [comment]
Okay, with Ultrapermissions i can use the timed group. But, in the syntax, how i put the timed group?

**Comment by ShaneBeee** [comment]
`[members of] group %string% [in [world] %world%] [for %timespan%])`
so it would just be `add player to members of group "group-here" for 1 hour`

**Comment by adfsklodsfhnuisgyb** [comment]
thx <3
